### ISSUE TITLE
unzip package

### ISSUE THREAD

**Issue by Rahimz** [vfarid/ssh-panel#1]
Some server may not have the unzip package. When I run the script on my server it stoped and said to install unzip.
You could add `sudo apt-get install unzip` to make it simpler.

**Comment by cr4zyfish** [comment]
why put the file in zip anyway? put them in directory so people can contribute. use git clone instead.

**Comment by vfarid** [comment]
Got clone is not proper solution for this job.

**Comment by vfarid** [comment]
Fixed in master
