### ISSUE TITLE
مشکل در اتصال، پس از نصب

### ISSUE THREAD

**Issue by RahmanSheykhhadi** [vfarid/ssh-panel#3]
بعد از نصب اسکریپت و تعریف کاربران؛ نه با پورت پیش فرض سرورم (5829) و نه با پورت ۲۲ نمی‌تونم به سرور وصل بشم. ارور میده 
kex_exchange_identification: Connection closed by remote host
از نرم افزار یا تنظیمات خاصی باید استفاده کنم پس از نصب؟

**Comment by vfarid** [comment]
این اسکریپت اصلا سرویس sshd رو لمس نمیکنه. به هیچ عنوان تاثیری روی لاگین شما نداره. تنها چیزی که به ذهنم میرسه اینه چون قبل از نصب، سیستم آپدیت میشه، شاید تو پروسه‌ی آپدیت مشکلی پیش اومده. از طریق پنل فروشنده یکبار سرور رو ریستارت کنید و با همون چورتی که همیشه وصل میشدید به سرور وصل بشید.
اگه باز مشکل حل نشد یا با VNC روی پنل فروشنده وارد بشید و چک کنید یا به پشتیبانی فروشنده بگید مشکل رو. در واقع مشکل اینه که بعد از آپدیت سیستم‌عامل، نمیتونید از طریق ssh به سرور وصل بشید.
