### ISSUE TITLE
Monitor Statistics does not work in Ubuntu 22

### ISSUE THREAD

**Issue by salario07** [vfarid/ssh-panel#4]
Hi, First of all, I want to express my appreciation for your valuable work.
It seems like the monitor statistics feature is not working on Ubuntu 22.

**Expected behavior:**
After installing the panel, I can see usage statistics per user.

**Actual behavior:**
After installing the panel, All statistics for all users remain 0 even when I'm connected to the SSH config for more than one hour. I'm sure that I downloaded more than 10 MB of data.

**Comment by vfarid** [comment]
Thanks for your feedback.
Actually the cron job will store usage stats in log file every 5 minutes. For the first time, please wait for 10-15 minutes and then check the result.
I've tested the script on Ubuntu22 one more time and it is working as expected.
In case you see no results again, please re-install the code. Make sure you have root access.
